# Azure Service Bus particulars

#Metric prefix used when SIM is enabled for your machine agent
#metricPrefix: Custom Metrics|Azure Service Bus|

#This will publish metrics to specific tier
#Instructions on how to retrieve the Component ID can be found in the Metric Prefix section of https://community.appdynamics.com/t5/Knowledge-Base/How-do-I-troubleshoot-missing-custom-metrics-or-extensions/ta-p/28695
metricPrefix: Server|Component:<COMPONENT_ID>|Custom Metrics|Azure Service Bus|

servers:
  - displayName: "Server 1"
    namespace: "CloudCollectorNS"
    resourceGroup: "cloud-collectors-rg"
    tenantId: "***REMOVED***"
    subscriptionId: "***REMOVED***"
    clientId: "***REMOVED***"
    clientSecret: "***REMOVED***"

    # Provide sasKeyName,sasKey or encryptedSasKeyName,encryptedSasKey
    #encryptedTenantId: ""
    #encryptedSubscriptionId: ""
    #encryptedClientId:
    #encryptedClientSecret:
    # Provide either include or exclude configuration.
    # If include and exclude are provided, will consider only include.
    # If include and exclude are not provided, will fetch everything.
    # Define queues to include. supports regex
    includeQueues: [".*"]
    # Define queues to exclude. supports regex
    excludeQueues: []
    # Define topics to include. supports regex
    includeTopics: [".*"]
    # Define topics to exclude. supports regex
    excludeTopics: []

encryptionKey: "welcome"

proxy:
  uri: ""
  username: ""
  password: ""
  #encryptedPassword: ""

#Number of threads
numberOfThreads: 10

# type once defined can not be changed later.
# type consists is made of: aggregationType.timeRollup.clusterRollup
queueMetrics:
  - name: "ActiveMessages"
    alias: "Active Message Count"
    multiplier: "1"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    delta: "false"
    fromQueue: "false"
  - name: "DeadletteredMessages"
    alias: "DeadLetter Message Count"
    multiplier: "1"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    delta: "false"
    fromQueue: "false"
  - name: "ScheduledMessages"
    alias: "Scheduled Message Count"
    multiplier: "1"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    delta: "false"
    fromQueue: "false"
  - name: "Messages"
    alias: "Message Count"
    multiplier: "1"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    delta: "false"
    fromQueue: "false"
  - name: "Size"
    alias: "Size In Bytes"
    multiplier: "1"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    delta: "false"
    fromQueue: "false"
  - name: "IncomingRequests"
    alias: "Incoming Requests"
    multiplier: "1"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    delta: "false"
    fromTopic: "false"
  - name: "SuccessfulRequests"
    alias: "Successful Requests"
    multiplier: "1"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    delta: "false"
    fromTopic: "false"
  - name: "ServerErrors"
    alias: "Server Errors"
    multiplier: "1"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    delta: "false"
    fromTopic: "false"
  - name: "UserErrors"
    alias: "User Errors"
    multiplier: "1"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    delta: "false"
    fromTopic: "false"
  - name: "ThrottledRequests"
    alias: "Throttled Requests"
    multiplier: "1"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    delta: "false"
    fromTopic: "false"
  - name: "TransferMessageCount"
    alias: "Transfer Message Count"
    multiplier: "1"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    delta: "false"
    fromQueue: "true"
  - name: "TransferDeadLetterMessageCount"
    alias: "Transfer DeadLetter Message Count"
    multiplier: "1"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    delta: "false"
    fromQueue: "true"
  - name: "MaxDeliveryCount"
    alias: "Max Delivery Count"
    multiplier: "1"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    delta: "false"
    fromQueue: "true"
  - name: "MaxSizeInMegabytes"
    alias: "Max Size In Megabytes"
    multiplier: "1"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    delta: "false"
    fromQueue: "true"
  - name: "Status"
    alias: "Status"
    multiplier: "1"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    delta: "false"
    fromQueue: "true"
    convert:
      Active: "1"
      Disabled: "2"
      Restoring: "3"
      SendDisabled: "4"
      ReceiveDisabled: "5"
      Creating: "6"
      Deleting: "7"
      Renaming: "8"
      Unknown: "9"

topicMetrics:
  - name: "ActiveMessages"
    alias: "Active Message Count"
    multiplier: "1"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    delta: "false"
    fromTopic: "false"
  - name: "DeadletteredMessages"
    alias: "DeadLetter Message Count"
    multiplier: "1"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    delta: "false"
    fromTopic: "false"
  - name: "ScheduledMessages"
    alias: "Scheduled Message Count"
    multiplier: "1"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    delta: "false"
    fromTopic: "false"
  - name: "Size"
    alias: "Size In Bytes"
    multiplier: "1"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    delta: "false"
    fromTopic: "false"
  - name: "IncomingRequests"
    alias: "Incoming Requests"
    multiplier: "1"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    delta: "false"
    fromTopic: "false"
  - name: "SuccessfulRequests"
    alias: "Successful Requests"
    multiplier: "1"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    delta: "false"
    fromTopic: "false"
  - name: "ServerErrors"
    alias: "Server Errors"
    multiplier: "1"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    delta: "false"
    fromTopic: "false"
  - name: "UserErrors"
    alias: "User Errors"
    multiplier: "1"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    delta: "false"
    fromTopic: "false"
  - name: "ThrottledRequests"
    alias: "Throttled Requests"
    multiplier: "1"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    delta: "false"
    fromTopic: "false"
  - name: "TransferMessageCount"
    alias: "Transfer Message Count"
    multiplier: "1"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    delta: "false"
    fromTopic: "true"
  - name: "TransferDeadLetterMessageCount"
    alias: "Transfer DeadLetter Message Count"
    multiplier: "1"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    delta: "false"
    fromTopic: "true"
  - name: "MaxSizeInMegabytes"
    alias: "Max Size In Megabytes"
    multiplier: "1"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    delta: "false"
    fromTopic: "true"
  - name: "Status"
    alias: "Status"
    multiplier: "1"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    delta: "false"
    fromTopic: "true"
    convert:
      Active: "1"
      Disabled: "2"
      Restoring: "3"
      SendDisabled: "4"
      ReceiveDisabled: "5"
      Creating: "6"
      Deleting: "7"
      Renaming: "8"
      Unknown: "9"