# Azure Service Bus particulars

# Number of threads to parallely execute Namespace requests to fetch Queue names and Topic names
namespaceThreads: 5
# Number of threads to parallely execute Queue stats request
queueThreads: 5
# Number of threads to parallely execute Topic stats request
topicThreads: 5

azure:
    subscriptionId: "4a19b866-6e53-4f09-89e3-46b3735e0a08"
    keyStoreLocation: "/Users/Muddam/AppDynamics/dummy/WindowsAzureKeyStore.jks"
    keyStorePassword: "test123"

# Azure Service Bus Namespaces
namespaces:
    -   namespace: "appdservicebus"
        queueStats: [size,incoming,outgoing,length,requests.total,requests.successful,requests.failed,requests.failed.internalservererror,requests.failed.serverbusy,requests.failed.other]
        excludeQueues: []
        topicStats: [size,incoming,requests.total,requests.successful,requests.failed,requests.failed.internalservererror,requests.failed.serverbusy,requests.failed.other]
        excludeTopics: []

#prefix used to show up metrics in AppDynamics
metricPrefix:  "Custom Metrics|Azure Service Bus|"